### ISSUE TITLE
[Feature] Add output attachment control for script-based tools

### ISSUE THREAD

**Issue by plusplusoneplusplus** [plusplusoneplusplus/mcp#106]
# [Feature] Add output attachment control for script-based tools

## Problem/Motivation

Currently, script-based tools defined in YAML configuration (`server/tools.yaml`) always return both stdout and stderr outputs. There's no way to configure which outputs should be included in the response, leading to potentially noisy or confusing results.

**Current Behavior:**
- All script-based tools always return both `output` (stdout) and `error` (stderr) fields
- No control over what gets included in the response
- Verbose debug information in stderr clutters successful responses
- No way to show stderr only on failures

## Proposed Solution

Add a `post_processing` configuration section to script-based tools in YAML that allows controlling which outputs are attached to the response.

### YAML Configuration Structure

```yaml
tools:
  deploy:
    enabled: true
    name: deploy
    type: script
    scripts:
      linux: bash {pwd}/deploy.sh
      darwin: bash {pwd}/deploy.sh
      windows: powershell -file {pwd}/deploy.ps1
    post_processing:
      attach_stdout: true              # Include stdout in output (default: true)
      attach_stderr: false             # Include stderr in output (default: true)  
      stderr_on_failure_only: true    # Only include stderr if return_code != 0 (default: false)
    inputSchema:
      type: object
      properties:
        environment:
          type: string
          enum: ["dev", "staging", "prod"]
      required: ["environment"]
```

### Configuration Options

| Option | Type | Default | Description |
|--------|------|---------|-------------|
| `attach_stdout` | boolean | `true` | Include stdout in the `output` field |
| `attach_stderr` | boolean | `true` | Include stderr in the `error` field |
| `stderr_on_failure_only` | boolean | `false` | Only include stderr when command fails (return_code != 0) |

## Acceptance Criteria

- [ ] Script-based tools can be configured with `post_processing.attach_stdout`
- [ ] Script-based tools can be configured with `post_processing.attach_stderr` 
- [ ] Script-based tools can be configured with `post_processing.stderr_on_failure_only`
- [ ] When `attach_stdout: false`, the `output` field is empty or excluded
- [ ] When `attach_stderr: false`, the `error` field is empty or excluded
- [ ] When `stderr_on_failure_only: true`, stderr is only included on command failure
- [ ] All existing script-based tools continue to work unchanged (backward compatibility)
- [ ] Configuration is completely optional with sensible defaults

### Files to Modify

1. **`mcp_tools/yaml_tools.py`**
   - Extend `YamlToolBase._execute_script()` method
   - Add post-processing logic after getting result from CommandExecutor
   - Parse `post_processing` configuration from `self._tool_data`

2. **`server/tools.yaml`**
   - Update example tools with post-processing configurations
   - Document the new configuration options

### Implementation Approach

```python
async def _execute_script(self, arguments: Dict[str, Any]) -> List[Dict[str, Any]]:
    # ... existing execution logic ...
    
    # Get result from command executor  
    result = await self._command_executor.execute_async(formatted_script)
    final_result = await self._command_executor.wait_for_process(result['token'])
    
    # Apply post-processing configuration
    post_config = self._tool_data.get("post_processing", {})
    processed_result = self._apply_output_attachment_config(final_result, post_config)
    
    return [{"type": "text", "text": self._format_result(processed_result)}]

def _apply_output_attachment_config(self, result: Dict, config: Dict) -> Dict:
    """Apply output attachment configuration to command result."""
    # Control stdout attachment
    if not config.get("attach_stdout", True):
        result["output"] = ""
    
    # Control stderr attachment
    attach_stderr = config.get("attach_stderr", True)
    stderr_on_failure_only = config.get("stderr_on_failure_only", False)
    
    if not attach_stderr or (stderr_on_failure_only and result.get("success", False)):
        result["error"] = ""
    
    return result
```

### 1. Deployment Tool (clean success responses)
```yaml
deploy:
  type: script
  scripts:
    linux: bash {pwd}/deploy.sh
  post_processing:
    attach_stdout: true
    stderr_on_failure_only: true  # Only show errors on failure
```

### 2. Health Check Tool (no stderr noise)
```yaml
health_check:
  type: script
  scripts:
    linux: curl -s http://localhost:8080/health
  post_processing:
    attach_stderr: false  # Ignore curl's verbose output
```

### 3. Validation Tool (errors only)
```yaml
validate_config:
  type: script
  scripts:
    linux: bash {pwd}/validate.sh
  post_processing:
    attach_stdout: false   # Only show validation errors
    attach_stderr: true
```

## Additional Context

This enhancement addresses a common pain point where script outputs contain verbose debug information that clutters the user experience. By providing granular control over output attachment, tools can present cleaner, more focused results while maintaining full backward compatibility.

**Related Files:**
- `mcp_tools/yaml_tools.py` (lines 211-426: `_execute_script` method)
- `server/tools.yaml` (lines 90-150: script-based tool examples)
- `mcp_tools/command_executor/executor.py` (output handling logic)
