### ISSUE TITLE
[Chore] Move test scripts from server/ to mcp_tools/tests/fixtures/

### ISSUE THREAD

**Issue by plusplusoneplusplus** [plusplusoneplusplus/mcp#112]
## Problem/Motivation

Currently, test scripts used by YAML-based tools are located in the `server/` directory alongside production code. This creates organizational issues:

1. **Mixed concerns**: Test scripts are mixed with production server code
2. **Unclear purpose**: Scripts in `server/` appear to be production utilities rather than test fixtures
3. **Maintenance confusion**: Developers may not realize these are test scripts and modify them inappropriately
4. **Testing best practices**: Test fixtures should be co-located with test code for better organization

**Current structure:**
```
server/
├── test_deploy.sh          # Test script for deployment tool
├── test_deploy.ps1         # Windows version of deployment test script
├── validate_config.sh      # Test script for validation tool (if exists)
├── validate_config.ps1     # Windows version of validation test script (if exists)
└── tools.yaml             # References these scripts with {pwd}/script_name
```

## Proposed Solution

Move all test scripts from `server/` to `mcp_tools/tests/fixtures/scripts/` and update the YAML configuration to reference the new location.

**Target structure:**
```
mcp_tools/tests/fixtures/
├── scripts/
│   ├── test_deploy.sh
│   ├── test_deploy.ps1
│   ├── validate_config.sh      # If exists
│   └── validate_config.ps1     # If exists
└── (existing YAML fixtures)
```

## Acceptance Criteria

- [ ] Create `mcp_tools/tests/fixtures/scripts/` directory
- [ ] Move `server/test_deploy.sh` to `mcp_tools/tests/fixtures/scripts/test_deploy.sh`
- [ ] Move `server/test_deploy.ps1` to `mcp_tools/tests/fixtures/scripts/test_deploy.ps1`
- [ ] Move any `validate_config.*` scripts if they exist
- [ ] Update `server/tools.yaml` to reference the new script locations
- [ ] Update script paths to use relative paths from the test fixtures directory
- [ ] Ensure all existing tests continue to pass
- [ ] Verify that YAML tools can still execute the moved scripts correctly
- [ ] Update any documentation that references the old script locations

## Technical Details

**Files to modify:**
- `server/tools.yaml` - Update script paths in tool definitions
- Move scripts from `server/` to `mcp_tools/tests/fixtures/scripts/`

**Current YAML references (in server/tools.yaml):**
```yaml
deploy:
  script: bash {pwd}/test_deploy.sh
  scripts:
    windows: powershell -file {pwd}/test_deploy.ps1
    darwin: bash {pwd}/test_deploy.sh
    linux: bash {pwd}/test_deploy.sh
```

**Proposed YAML updates:**
```yaml
deploy:
  script: bash {pwd}/../mcp_tools/tests/fixtures/scripts/test_deploy.sh
  scripts:
    windows: powershell -file {pwd}/../mcp_tools/tests/fixtures/scripts/test_deploy.ps1
    darwin: bash {pwd}/../mcp_tools/tests/fixtures/scripts/test_deploy.sh
    linux: bash {pwd}/../mcp_tools/tests/fixtures/scripts/test_deploy.sh
```

**Testing considerations:**
- Verify that `{pwd}` parameter resolution works correctly with the new paths
- Ensure cross-platform compatibility (Windows/macOS/Linux)
- Test that script execution permissions are preserved during the move
- Validate that existing YAML tool tests continue to pass

## Additional Context

This refactoring improves code organization by:
1. **Separating test fixtures from production code**
2. **Following testing best practices** by co-locating test scripts with test code
3. **Improving maintainability** by making it clear these are test utilities
4. **Reducing confusion** for new developers about the purpose of these scripts

**Related:**
- This follows the existing pattern where YAML test fixtures are in `mcp_tools/tests/fixtures/`
- The `scripts/` subdirectory provides clear organization for executable test fixtures
- This change supports the post-processing feature implementation in issue #106

**Priority:** Low - This is a housekeeping task that improves organization but doesn't affect functionality
