### ISSUE TITLE
[Enhancement] Add category field to YAML tools for better organization and correlation

### ISSUE THREAD

**Issue by plusplusoneplusplus** [plusplusoneplusplus/mcp#174]
## Problem/Motivation

Currently, YAML tools defined in `tools.yaml` lack a way to categorize or group related tools together. This makes it difficult to:

- Organize tools by functional area (e.g., deployment, monitoring, validation)
- Correlate related tools that work together as part of a workflow
- Filter or display tools by category in UIs
- Understand the logical grouping of tools in large tool collections
- Implement category-based permissions or access controls

## Proposed Solution

Add an optional `category` field to YAML tool definitions that allows tools to be grouped and correlated by functional area or purpose.

### Implementation Details

1. **Add Category Field**: Extend the YAML tool schema to include an optional `category` string field
2. **Update Tool Loading**: Modify `YamlToolBase` to capture and expose the category information
3. **API Integration**: Include category information in tool metadata and API responses
4. **Backward Compatibility**: Ensure existing tools without categories continue to work (default to "uncategorized" or similar)

### Backend Changes
- [ ] Extend YAML tool schema to support optional `category` field
- [ ] Update `YamlToolBase` class to store and expose category information
- [ ] Modify tool loading logic in `yaml_tools.py` to preserve category data
- [ ] Add category information to tool metadata in plugin registry
- [ ] Update API endpoints to include category information where appropriate

### Schema Updates
- [ ] Add `category` field validation to YAML tool loading
- [ ] Ensure category field is optional with sensible defaults
- [ ] Support string values for categories (e.g., "deployment", "monitoring", "validation")

### API Enhancements
- [ ] Include category in tool listing endpoints
- [ ] Add filtering capability by category in relevant APIs
- [ ] Update tool metadata responses to include category information

### Documentation
- [ ] Update tool.example.yaml with category examples
- [ ] Document category field in YAML tool documentation
- [ ] Provide examples of common category naming conventions

### Files to Modify

**Core Implementation:**
- `mcp_tools/yaml_tools.py`: Update `YamlToolBase` class to handle category field
- `mcp_tools/plugin.py`: Include category in tool metadata
- `server/api.py`: Add category to API responses where relevant

**Documentation/Examples:**
- `mcp_tools/tool.example.yaml`: Add category examples
- `server/tools.yaml`: Add categories to existing tools as examples

### Example YAML Structure

```yaml
tools:
  deploy:
    enabled: true
    name: deploy
    category: deployment  # NEW: Category field
    description: Deploy the application asynchronously
    type: script
    # ... rest of tool definition

  health_check:
    enabled: true
    name: health_check
    category: monitoring  # NEW: Category field
    description: Check application health status
    type: script
    # ... rest of tool definition

  validate_config:
    enabled: true
    name: validate_config
    category: validation  # NEW: Category field
    description: Validate configuration files
    type: script
    # ... rest of tool definition
```

### Implementation Notes

1. **YamlToolBase Enhancement**:
   ```python
   class YamlToolBase(ToolInterface):
       def __init__(self, tool_name=None, tool_data=None, command_executor=None):
           # ... existing initialization ...
           self._category = tool_data.get("category", "uncategorized")
       
       @property
       def category(self) -> str:
           """Get the tool category."""
           return self._category
   ```

2. **Plugin Registry Integration**:
   - Add category to tool metadata in `get_available_plugins()`
   - Support category-based filtering in tool discovery

3. **API Response Enhancement**:
   - Include category in tool listing responses
   - Add optional category filtering parameters

### Workflow Organization
```yaml
# Deployment workflow tools
deploy:
  category: deployment
validate_deployment:
  category: deployment
rollback:
  category: deployment

# Monitoring workflow tools  
health_check:
  category: monitoring
check_logs:
  category: monitoring
alert_status:
  category: monitoring
```

### UI/UX Benefits
- Group tools by category in tool selection interfaces
- Create category-based navigation in web UIs
- Enable category-specific tool recommendations
- Support category-based search and filtering

### Administrative Benefits
- Implement category-based access controls
- Generate category-specific documentation
- Monitor tool usage by functional area
- Organize tool maintenance by category

## Additional Context

This enhancement provides:
- **Better Organization**: Logical grouping of related tools
- **Improved Discoverability**: Easier to find tools by functional area
- **Enhanced UX**: Category-based filtering and organization in UIs
- **Workflow Support**: Clear correlation between tools that work together
- **Scalability**: Better tool management as tool collections grow

The implementation should be backward compatible, with existing tools continuing to work without modification while new tools can optionally specify categories.

## Priority

Medium - This is an organizational improvement that will significantly enhance tool management and user experience as the tool ecosystem grows.
