### ISSUE TITLE
[Chore] Add Neo4j Development Environment Setup and Documentation

### ISSUE THREAD

**Issue by plusplusoneplusplus** [plusplusoneplusplus/mcp#277]
## Problem/Motivation

To support the Neo4j Graph Interface implementation (#273-#276), we need to set up a proper development environment with Neo4j database, create setup documentation, and provide development tools for testing and debugging the graph interface.

## Proposed Solution

Create comprehensive development environment setup including:

1. **Neo4j Database Setup**: Docker configuration for local development
2. **Development Documentation**: Setup guides and best practices
3. **Testing Infrastructure**: Test database configuration and fixtures
4. **Development Tools**: Scripts for database management and debugging
5. **CI/CD Integration**: Automated testing with Neo4j in CI pipeline

### Database Setup
- [ ] Docker Compose configuration for Neo4j development database
- [ ] Environment variable configuration for different environments
- [ ] Database initialization scripts with sample data
- [ ] Backup and restore scripts for development data

### Documentation
- [ ] Developer setup guide in `docs/development/neo4j-setup.md`
- [ ] Graph modeling best practices guide
- [ ] Troubleshooting guide for common issues
- [ ] API documentation for graph interface components

### Testing Infrastructure
- [ ] Test database configuration separate from development
- [ ] Test fixtures with sample graph data
- [ ] Integration test setup with Docker
- [ ] Performance testing framework

### Development Tools
- [ ] Database management scripts (reset, seed, backup)
- [ ] Graph visualization tools for debugging
- [ ] Query debugging utilities
- [ ] Data migration scripts

### CI/CD Integration
- [ ] GitHub Actions workflow with Neo4j service
- [ ] Automated testing against multiple Neo4j versions
- [ ] Integration test coverage reporting
- [ ] Performance regression testing

### Files to Create:
- `docker/neo4j/docker-compose.yml`
- `docker/neo4j/Dockerfile`
- `docker/neo4j/init-scripts/01-create-indexes.cypher`
- `docker/neo4j/init-scripts/02-sample-data.cypher`
- `docs/development/neo4j-setup.md`
- `docs/development/graph-modeling-guide.md`
- `docs/api/graph-interface.md`
- `scripts/neo4j-dev-setup.sh`
- `scripts/neo4j-reset.sh`
- `scripts/neo4j-backup.sh`
- `.github/workflows/neo4j-tests.yml`
- `utils/graph_interface/dev_tools/`
- `utils/graph_interface/tests/fixtures/sample_data.py`

### Docker Configuration:
```yaml
# docker/neo4j/docker-compose.yml
version: '3.8'
services:
  neo4j:
    image: neo4j:5.15-community
    environment:
      NEO4J_AUTH: neo4j/development
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - ./init-scripts:/docker-entrypoint-initdb.d
    
  neo4j-test:
    image: neo4j:5.15-community
    environment:
      NEO4J_AUTH: neo4j/test
      NEO4J_PLUGINS: '["apoc"]'
    ports:
      - "7475:7474"
      - "7688:7687"
    volumes:
      - neo4j_test_data:/data
```

### Environment Configuration:
```bash
# Development environment
NEO4J_URI=bolt://localhost:7687
NEO4J_USERNAME=neo4j
NEO4J_PASSWORD=development
NEO4J_DATABASE=graph_db

# Test environment  
NEO4J_TEST_URI=bolt://localhost:7688
NEO4J_TEST_USERNAME=neo4j
NEO4J_TEST_PASSWORD=test
NEO4J_TEST_DATABASE=test_graph
```

### GitHub Actions Workflow:
```yaml
name: Neo4j Integration Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      neo4j:
        image: neo4j:5.15-community
        env:
          NEO4J_AUTH: neo4j/test
        ports:
          - 7687:7687
        options: >-
          --health-cmd "cypher-shell -u neo4j -p test 'RETURN 1'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
```

### Development Scripts:
```bash
#!/bin/bash
# scripts/neo4j-dev-setup.sh
echo "Setting up Neo4j development environment..."
docker-compose -f docker/neo4j/docker-compose.yml up -d neo4j
echo "Waiting for Neo4j to start..."
sleep 30
echo "Creating indexes and sample data..."
# Run initialization scripts
```

### Sample Data Fixtures:
```python
# utils/graph_interface/tests/fixtures/sample_data.py
SAMPLE_TASKS = [
    {
        "id": "task-001",
        "labels": ["Task"],
        "properties": {
            "name": "Setup Database",
            "status": "pending",
            "priority": "high"
        }
    },
    # ... more sample data
]

SAMPLE_DEPENDENCIES = [
    {
        "type": "DEPENDS_ON",
        "start_node_id": "task-002",
        "end_node_id": "task-001",
        "properties": {"dependency_type": "hard"}
    }
]
```

## Additional Context

This setup should support:
- **Local Development**: Easy setup for developers working on graph features
- **Testing**: Isolated test environment with predictable data
- **CI/CD**: Automated testing in GitHub Actions
- **Debugging**: Tools to inspect and visualize graph data during development
- **Performance Testing**: Benchmarking tools for large graph operations

### Documentation Structure:
```
docs/development/
├── neo4j-setup.md           # Getting started guide
├── graph-modeling-guide.md  # Best practices for modeling
├── troubleshooting.md       # Common issues and solutions
└── performance-tuning.md    # Optimization guidelines

docs/api/
├── graph-interface.md       # API documentation
├── examples.md             # Usage examples
└── migration-guide.md      # Upgrading and migration
```

## Dependencies

- Should be implemented alongside or before #273 (Core Infrastructure)
- Supports all subsequent graph interface issues (#274-#276)

## Related Issues

- #273 - Neo4j Graph Interface Core Infrastructure (supports)
- #274 - Node and Relationship Managers (supports)
- #275 - High-Level Graph Manager (supports)
- #276 - Task Management Integration (supports)
