### ISSUE TITLE
[Enhancement] Add Windows support to GitHub Actions CI workflow

### ISSUE THREAD

**Issue by plusplusoneplusplus** [plusplusoneplusplus/mcp#74]
## Problem/Motivation

The current GitHub Actions workflow only runs tests on Ubuntu Linux (`runs-on: ubuntu-latest`), but the codebase already has extensive Windows support built-in. Adding Windows to the CI workflow would:

1. **Ensure Windows compatibility** is maintained as the codebase evolves
2. **Catch Windows-specific issues** early in development
3. **Validate existing Windows support** that's already implemented
4. **Provide confidence** for Windows users of the MCP tools

## Evidence of Existing Windows Support

The codebase already includes comprehensive Windows support:

**Command Executor Windows Support:**
- Platform detection: `self.os_type = platform.system().lower()`
- Windows-specific command preparation: `cmd.exe /c "{command} > ..."`
- Windows process handling and termination

**Windows-Specific Tests:**
- `TestWindowsCommands` class in `test_command_executor_integration.py`
- Windows command tests: `cmd /c echo`, `dir`, `type`, `where`
- Platform-specific test logic throughout the test suite

**Browser Tools Windows Support:**
- Windows-specific ChromeDriver and EdgeDriver setup
- Windows path handling and driver detection
- Windows process termination commands (`taskkill /F /IM`)

**Cross-Platform Dependencies:**
- All major dependencies (psutil, playwright, selenium, etc.) support Windows
- Python 3.11+ requirement is Windows-compatible

## Proposed Solution

Update the GitHub Actions workflow to include a Windows runner alongside the existing Ubuntu runner using a matrix strategy.

## Acceptance Criteria

- [ ] GitHub Actions workflow runs tests on both Ubuntu and Windows
- [ ] Windows-specific tests pass in CI environment
- [ ] Windows runner uses the same Python version (3.11) as Ubuntu
- [ ] Windows runner installs and uses `uv` for package management
- [ ] Playwright browsers are properly installed on Windows
- [ ] Test script execution works on Windows (may need `.bat` equivalent or PowerShell)
- [ ] All existing functionality continues to work on both platforms
- [ ] CI workflow completes successfully on both platforms

## Technical Implementation

**Proposed Workflow Changes:**

```yaml
name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install uv (Unix)
        if: runner.os != 'Windows'
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          
      - name: Install uv (Windows)
        if: runner.os == 'Windows'
        run: |
          irm https://astral.sh/uv/install.ps1 | iex
          echo "$env:USERPROFILE\.cargo\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          
      - name: Create virtual environment
        run: uv venv
        
      - name: Install dependencies (Unix)
        if: runner.os != 'Windows'
        run: |
          source .venv/bin/activate
          uv pip install pytest pytest-asyncio
          uv pip install -e .
          
      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          .venv\Scripts\activate
          uv pip install pytest pytest-asyncio
          uv pip install -e .
          
      - name: Install Playwright Browsers
        run: |
          # Activate virtual environment based on OS
          if [ "$RUNNER_OS" == "Windows" ]; then
            .venv/Scripts/activate
          else
            source .venv/bin/activate
          fi
          playwright install chromium
        shell: bash

      - name: Run tests (Unix)
        if: runner.os != 'Windows'
        run: |
          source .venv/bin/activate
          chmod +x ./scripts/run_tests.sh
          ./scripts/run_tests.sh
          
      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        run: |
          .venv\Scripts\activate
          # May need to create run_tests.bat or use PowerShell equivalent
          python -m pytest --tb=short
```

**Alternative Approach - Cross-Platform Script:**
Instead of OS-specific steps, we could modify the test script to be cross-platform or create a Python-based test runner.

## Considerations and Challenges

**Potential Issues to Address:**

1. **Test Script Compatibility**: The current `run_tests.sh` is a bash script that won't run natively on Windows
   - **Solution**: Create a PowerShell equivalent or Python-based test runner
   - **Alternative**: Use Git Bash or WSL on Windows runner

2. **Path Separators**: Windows uses backslashes, Unix uses forward slashes
   - **Status**: Already handled in the codebase using `os.path` and `pathlib`

3. **Command Differences**: Windows uses different commands than Unix
   - **Status**: Already handled in `CommandExecutor` with platform detection

4. **Process Management**: Different process handling between platforms
   - **Status**: Already handled using `psutil` and platform-specific logic

5. **Browser Driver Setup**: Different driver paths and installation methods
   - **Status**: Already implemented in browser tools

**Benefits:**

1. **Early Detection**: Catch Windows-specific issues before release
2. **User Confidence**: Windows users can trust the tools work on their platform
3. **Comprehensive Testing**: Validate the existing Windows support code
4. **Cross-Platform Reliability**: Ensure features work consistently across platforms

## Migration Strategy

1. **Phase 1**: Add Windows runner with basic test execution
2. **Phase 2**: Ensure all tests pass on Windows (may require minor fixes)
3. **Phase 3**: Optimize Windows CI performance and reliability
4. **Phase 4**: Consider adding macOS runner for complete cross-platform support

This enhancement will significantly improve the project's cross-platform reliability and user confidence.
