### ISSUE TITLE
[Feature] Implement hierarchical configuration system for output truncation

### ISSUE THREAD

**Issue by plusplusoneplusplus** [plusplusoneplusplus/mcp#82]
## Problem/Motivation
The MCP framework needs a flexible configuration system to manage output truncation settings across different levels (task, tool, user, system) to prevent context window overflow while maintaining user control.

## Proposed Solution
Implement a hierarchical configuration manager that resolves truncation settings in priority order:
1. Task-level (highest priority)
2. Tool-level (from YAML tool definitions)
3. User-level (user preferences)
4. System-level (global defaults)

## Acceptance Criteria
- [ ] Create `TruncationConfig` class with schema validation
- [ ] Implement hierarchical config resolution logic
- [ ] Support YAML tool definition parsing for truncation settings
- [ ] Add user-level configuration via environment variables
- [ ] Provide system-level defaults
- [ ] Include comprehensive unit tests for config resolution
- [ ] Add configuration validation and error handling

## Technical Details
**Files to create/modify:**
- `utils/output_processor/config.py` - Configuration manager
- `utils/output_processor/schemas.py` - Configuration schemas
- `tests/utils/output_processor/test_config.py` - Unit tests

**Configuration Schema:**
```yaml
truncation:
  strategy: "head_tail"  # head_tail, smart_summary, size_limit, none
  max_chars: 50000      # ~50KB default
  max_lines: 1000       # Line-based limit
  head_lines: 100       # Lines to keep from start
  tail_lines: 100       # Lines to keep from end
  preserve_errors: true # Always include error messages
  preserve_warnings: true # Always include warnings
  content_detection: true # Detect and preserve structured data
```

## Dependencies
- None (foundational component)

## Priority
High - Required for all other truncation features
