### ISSUE TITLE
[Feature] Implement size limit truncation strategy

### ISSUE THREAD

**Issue by plusplusoneplusplus** [plusplusoneplusplus/mcp#86]
## Problem/Motivation
Need a simple, predictable truncation strategy that enforces hard character limits while attempting to break at natural boundaries (words, lines) for better readability.

## Proposed Solution
Implement a size limit strategy that provides hard cutoff at character limits with intelligent boundary detection to avoid breaking words or lines when possible.

## Acceptance Criteria
- [ ] Create `SizeLimitStrategy` class implementing `TruncationStrategy`
- [ ] Support hard character limit enforcement
- [ ] Implement intelligent boundary detection (word, line breaks)
- [ ] Add configurable truncation position (end, middle, start)
- [ ] Include clear truncation indicators
- [ ] Handle various text encodings correctly
- [ ] Add comprehensive unit tests with edge cases
- [ ] Performance optimization for large content

## Technical Details
**Files to create/modify:**
- `utils/output_processor/strategies/size_limit.py` - Size limit strategy implementation
- `tests/utils/output_processor/strategies/test_size_limit.py` - Unit tests

**Strategy Features:**
- Hard character limit enforcement
- Word boundary preservation
- Line boundary preservation  
- Configurable truncation position
- Unicode-aware character counting
- Clear truncation indicators

**Configuration Options:**
```yaml
truncation:
  strategy: "size_limit"
  max_chars: 50000      # Hard character limit
  break_on_words: true  # Prefer word boundaries
  break_on_lines: true  # Prefer line boundaries
  position: "end"       # end, middle, start
```

**Boundary Detection:**
- Word boundaries (whitespace, punctuation)
- Line boundaries (newlines)
- Sentence boundaries (periods, exclamation, question marks)
- Unicode character boundaries

## Use Cases
- Simple character-based truncation
- Content with strict size requirements
- Fallback strategy for other methods
- Performance-critical scenarios

## Dependencies
- Issue #83 (Core truncation engine) - Required for base strategy classes

## Priority
Low - Simple strategy, useful as fallback
