### ISSUE TITLE
[Feature] Integrate truncation system with CommandExecutor

### ISSUE THREAD

**Issue by plusplusoneplusplus** [plusplusoneplusplus/mcp#87]
## Problem/Motivation
The CommandExecutor tool needs to be integrated with the truncation system to automatically handle large command outputs and prevent context window overflow in MCP sessions.

## Proposed Solution
Integrate the truncation engine with CommandExecutor to automatically apply truncation based on YAML tool definitions and user configurations, providing seamless output management.

## Acceptance Criteria
- [ ] Modify CommandExecutor to use truncation engine
- [ ] Add YAML tool definition support for truncation config
- [ ] Implement automatic truncation for command outputs
- [ ] Add truncation metadata to command results
- [ ] Support per-command truncation overrides
- [ ] Maintain backward compatibility with existing usage
- [ ] Add comprehensive integration tests
- [ ] Include performance impact measurements

## Technical Details
**Files to create/modify:**
- `mcp_tools/command_executor/executor.py` - Add truncation integration
- `config/tools.yaml` - Add truncation configuration for command_executor
- `tests/mcp_tools/command_executor/test_truncation_integration.py` - Integration tests

**Integration Points:**
- Automatic truncation of command stdout/stderr
- YAML configuration parsing
- Truncation metadata in response
- Error preservation for failed commands
- Performance monitoring

**YAML Configuration Example:**
```yaml
command_executor:
  name: "command_executor"
  description: "Execute system commands"
  truncation:
    strategy: "head_tail"
    max_chars: 50000
    max_lines: 1000
    head_lines: 100
    tail_lines: 100
    preserve_errors: true
    preserve_warnings: true
```

**Response Format:**
```json
{
  "stdout": "truncated_output",
  "stderr": "error_output", 
  "exit_code": 0,
  "truncation": {
    "applied": true,
    "strategy": "head_tail",
    "original_size": 150000,
    "truncated_size": 45000
  }
}
```

## Use Cases
- Large command outputs (logs, file listings)
- Build/compilation results
- System diagnostics
- File processing commands

## Dependencies
- Issue #82 (Configuration system) - Required for YAML config
- Issue #83 (Core truncation engine) - Required for truncation functionality
- Issue #84 (Head-tail strategy) - Recommended default strategy

## Priority
High - Critical integration for preventing context overflow
