### ISSUE TITLE
[Feature] Create generic tool wrapper for universal truncation support

### ISSUE THREAD

**Issue by plusplusoneplusplus** [plusplusoneplusplus/mcp#88]
## Problem/Motivation
Need a generic wrapper system that can automatically apply truncation to any MCP tool without requiring individual tool modifications, enabling universal truncation support across the entire framework.

## Proposed Solution
Create a generic tool wrapper that intercepts tool responses and applies truncation based on YAML tool definitions, providing automatic truncation for all tools in the MCP ecosystem.

## Acceptance Criteria
- [ ] Create `ToolWrapper` class for generic tool interception
- [ ] Implement automatic response truncation for any tool
- [ ] Support YAML-based tool configuration loading
- [ ] Add tool-specific truncation overrides
- [ ] Maintain original tool interface compatibility
- [ ] Include response metadata with truncation info
- [ ] Add comprehensive tests with various tool types
- [ ] Provide performance monitoring and metrics

## Technical Details
**Files to create/modify:**
- `utils/output_processor/tool_wrapper.py` - Generic tool wrapper
- `utils/output_processor/tool_registry.py` - Tool configuration registry
- `config/tools.yaml` - Universal tool configuration file
- `tests/utils/output_processor/test_tool_wrapper.py` - Unit tests

**Wrapper Architecture:**
- Decorator pattern for tool wrapping
- Automatic response interception
- YAML configuration loading
- Tool-specific config resolution
- Response transformation pipeline

**YAML Configuration Structure:**
```yaml
# Universal tool configurations
browser_automation:
  truncation:
    strategy: "smart_summary"
    max_chars: 30000
    preserve_errors: true

file_operations:
  truncation:
    strategy: "head_tail"
    max_chars: 20000
    head_lines: 50
    tail_lines: 50

default:
  truncation:
    strategy: "size_limit"
    max_chars: 50000
```

**Wrapper Usage:**
```python
@tool_wrapper
async def my_tool(params):
    # Tool implementation
    return large_response

# Automatic truncation applied based on YAML config
```

**Response Enhancement:**
```json
{
  "original_response": "tool_output",
  "truncation": {
    "applied": true,
    "strategy": "smart_summary",
    "original_size": 100000,
    "final_size": 25000,
    "config_source": "yaml_tool_definition"
  }
}
```

## Use Cases
- Universal truncation for all MCP tools
- Consistent output management across tools
- Easy configuration without code changes
- Backward compatibility for existing tools

## Dependencies
- Issue #82 (Configuration system) - Required for YAML config loading
- Issue #83 (Core truncation engine) - Required for truncation functionality

## Priority
Medium - Enables universal truncation support
